# -*- coding: utf-8 -*-
"""Weather_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H9yppr4zUuoe28e-xe8drF09FBvc7E3N
"""

#Project 01

import pandas as pd
data = pd.read_csv("Weather_Analysis.csv")

data

data.head()

data.shape

data.index

data.columns

data.dtypes

data['Weather'].unique()

data.nunique()

data.count()

data['Weather'].value_counts()

data.info()

"""Q1) FIND ALL UNIQUE 'WIND SPEED' VALUES IN THE DATA"""

data.head(2)

data['Wind Speed_km/h'].nunique()

data['Wind Speed_km/h'].unique()

"""Q2) FIND THE NUMBER OF TIMES WHEN THE 'WEATHER IS EXACTLY CLEAR'"""

data.head(2)

data.Weather.value_counts()

#filtering method
data[data.Weather == 'Clear']

#groupby
data.groupby('Weather').get_group('Clear')

"""Q3) FIND THE NUMBER OF TIMES WHEN THE 'WIND SPEED WAS EXACTLY 4 KM/H'"""

data[data['Wind Speed_km/h'] == 4]

"""Q4) FIND ALL THE NULL VALUES IN THE DATA"""

data.isnull().sum()

data.notnull().sum()

"""Q5) RENAME THE COLUMNE 'WEATHER' OF THE DATAFRAME TO 'WEATHER CONDITION'"""

#data.rename(columns = {'Weather': 'Weather Condition'}) #temporary
data.rename(columns = {'Weather': 'Weather Condition'}, inplace = True) #permanent

"""Q6) WHAT IS THE MEAN 'VISIBILITY'"""

data.Visibility_km.mean()

"""Q7) WHAT IS THE STANDARD DEVIATION OF 'PRESSURE' IN THIS DATA"""

data.Press_kPa.std()

"""Q8) WHAT IS THE VARIANCE OF 'RELATIVE HUMIDITY' IN THIS DATA"""

data['Rel Hum_%'].var()

"""Q9) FIND ALL INSTANCES WHEN 'SNOW' WAS RECORDED"""

data[data['Weather Condition'] == 'Snow']

data[data['Weather Condition'].str.contains('Snow')]

"""Q10) FIND ALL INSTANCES WHEN 'WIND SPEED IS ABOVE 24' AND 'VISIBILITY IS 25'"""

data[(data['Wind Speed_km/h']>24) & (data.Visibility_km == 25)]

"""Q11) WHAT IS THE MEAN VALUE OF EACH COLUMN AGAINST EACH 'WEATHER CONDITION'"""

data.groupby('Weather Condition').mean()

"""Q12) WHAT IS THE MINIMUM AND MAXIMUM VALUE OF EACH COLUMN AGAINST EACH 'WEATHER CONDITION'"""

data.groupby('Weather Condition').min()

data.groupby('Weather Condition').max()

"""Q13) SHOW ALL THE RECORDS WHERE WEATHER CONDITION IS FOG."""

data[data['Weather Condition'] == 'Fog']

"""Q14) FIND ALL INSTANCES WHEN 'WEATHER IS CLEAR' OR 'VISIBILITY IS ABOVE 40'."""

data[(data['Weather Condition'] == 'Clear') | (data.Visibility_km > 40)]

"""Q15) FIND ALL INSTANCES WHEN :
  A. 'WEATHER IS CLEAR' AND 'RELATIVE HUMIDITY IS GREATER THAN 50'
    OR
  B. 'VISIBILITY IS ABOVE 40'
"""

data[((data['Weather Condition'] == 'Clear') & (data['Rel Hum_%'] > 50) | (data.Visibility_km > 40))]